### ISSUE TITLE
Include changes from v1.8.0 of Lightspeed eCom API client

### ISSUE THREAD

**Issue by ls-michielrensen** [gunharth/laravel-lightspeed-api#3]
Just for reference, include the changes from the upcoming v1.8.0 of the Lightspeed eCom API PHP Client https://github.com/SEOshop/API-PHP-Client/tree/v1.8.0

**Comment by gunharth** [comment]
@michielrensen Thanks - will do ... when do you think it will be released?

**Comment by ls-michielrensen** [comment]
The current plan is next Monday Dec 5th.

**Comment by gunharth** [comment]
Perfect

**Comment by ls-michielrensen** [comment]
@gunharth v1.8.0 just got released, in the release notes you can find what's changed: https://github.com/SEOshop/API-PHP-Client/releases/tag/v1.8.0

**Comment by gunharth** [comment]
@michielrensen PS: thx for the @mention on your project!
